# “Java 编程语言基础”实验报告
##  异常相关
***
***
***
##  异常
异常都是从Throwable类派生出来的，而Throwable类是直接从Object类继承而来。

### 分类
异常通常有四类：
+ Error：系统内部错误，这类错误由系统进行处理，程序本身无需捕获处理
+ Exception：可以处理的异常
+ RuntimeException：可以捕获，也可以不捕获的异常
+ 继承 Exception 的其他类：必须捕获，通常在 API 文档中会说明这些方法抛出哪些异常

RuntimeExcption 异常(运行时异常)通常有以下几种：
+ 错误的类型转换
+ 数组访问越界
+ 访问 null 指针
+ 算术异常

非 RuntimeException（受查异常）一般有：
+ 打开一个不存在的文件
+ 没有找到具有指定名称的类
+ 操作文件异常

受查异常是编译器要求必须处理的异常，必须使用 try catch 处理，或者向上抛出，给上层处理。

### 声明及抛出
***throw* 抛出异常**

当程序运行时数据出现错误或者我们不希望发生的情况出现的话，可以通过抛出异常来处理。

***throws* 声明异常**

throws 用于声明异常，表示该方法可能会抛出的异常。如果声明的异常中包括 checked 异常（受查异常），那么调用者必须处理该异常或者使用 throws 继续向上抛出。throws 位于方法体前，多个异常使用,分割。

### 捕获异常
通常抛出异常后，还需要将异常捕获。使用try和catch语句块来捕获异常，有时候还会用到finally。

对于上述三个关键词所构成的语句块，try语句块是必不可少的，catch和finally语句块可以根据情况选择其一或者全选。你可以把可能发生错误或出现问题的语句放到try语句块中，将异常发生后要执行的语句放到catch语句块中，而finally语句块里面放置的语句，不管异常是否发生，它们都会被执行。**注意：catch语句块可以同时存在多个，用来分别应对不同的异常情况**

**捕获异常对于系统而言，其开销非常大，所以应尽量减少该语句块中放置的语句。**

### 自定义异常
    public class MyAriException extends ArithmeticException {

        public MyAriException() {

        }
        //实现默认的无参构造方法

        public MyAriException(String msg) {
            super(msg);
        }
        //实现可以自定义输出信息的构造方法，将待输出信息作为参数传入即可
    }

    import java.util.Arrays;

    public class ExceptionTest {
        public static void main(String[] args) {
            int[] array = new int[5];

            Arrays.fill(array, 5);

            for (int i = 4; i > -1; i--) {

                if (i == 0) {

                    throw new MyAriException("There is an exception occured.");
                }

                System.out.println("array[" + i + "] / " + i + " = " + array[i] / i);
            }
        }
    }
实验结果如图：

![自定义异常](https://dn-simplecloud.shiyanlou.com/courses/uid1080185-20190531-1559302642633)

##  异常堆栈
当异常抛出后，可以通过异常堆栈追踪程序的运行轨迹。

    public class ExceptionStackTrace {
        private static void method1() {
            method2();
        }

        private static void method2() {
            throw new NullPointerException();
        }
        public static void main(String[] args) {
            try {
                method1();
            } catch (Exception e) {
                //打印堆栈轨迹
                e.printStackTrace();
            }
        }
    }
实验结果如图：

![异常堆栈](https://dn-simplecloud.shiyanlou.com/courses/uid1080185-20190531-1559302844294)

异常信息中首先打印的是距离抛出异常最近的语句，接着是调用该方法的方法，一直到最开始被调用的方法。从下往上看，就可以得出程序运行的轨迹。
